Feature/sign with apple in release 1.9
nickfedchenko/grocerylist1 pull request #25
Opened 2023-02-16 11:53 UTC by MollachievShamil

2023-02-17 08:03 UTC, ChuldumKhandy approved these changes

2023-02-17 10:06 UTC, FedmanCassad requested changes

2023-02-17 10:06 UTC, FedmanCassad commented on GroceryList/ViewControllers/SignUpViewCntroller/SignUpViewModel.swift
> +            createAccountAndLogIn(email: email)
Ок в случае если это новая рега, отрабатывает этот else.  Вопросов нет.

2023-02-17 10:06 UTC, FedmanCassad commented on GroceryList/ViewControllers/SignUpViewCntroller/SignUpViewModel.swift
> +        checkMail(text: email) { [weak self] isMailExist in
Далее ты проверяешь есть ли такое мыло в зареганных - окей, босс, и если нет сохраняешь криденшелы и регаешься на бэке, но:
1) у тебя этот метод одинаково работает и для signIn и singUp стейта
2) Криденшелы в keychain должны сохраняться только после успешной реги или успешного логина, а не заранее.
более того, ты же понимаешь, что гард в 173 строке сработает лишь в скоупе замыкания? и SignUp выполнится независимо от него и более того возможно даже раньше чем успеет вернуться флаг isMailERxist. То есть в самом замыкании дальнейшие действия надо производить.

2023-02-20 08:11 UTC, FedmanCassad approved these changes
Выглядит как правда

2023-02-20 08:49 UTC, merged